### PR TITLE
Fixup bitshift issue on 32-bit

### PR DESCRIPTION
**Pull request by nileshpatra**
Currently nmodl fails to compile on 32-bit machines with:
```
/<<PKGBUILDDIR>>/src/symtab/symbol_properties.hpp:217:17: warning: left shift count >= width of type [-Wshift-count-overflow]
  217 |     define = 1L << 32,
      |              ~~~^~~~~
/<<PKGBUILDDIR>>/src/symtab/symbol_properties.hpp:217:17: error: right operand of shift expression ‘(1 << 32)’ is greater than or equal to the precision 32 of the left operand [-fpermissive]
/<<PKGBUILDDIR>>/src/symtab/symbol_properties.hpp:217:20: error: enumerator value for ‘define’ is not an integer constant
  217 |     define = 1L << 32,
      |                    ^~
/<<PKGBUILDDIR>>/src/symtab/symbol_properties.hpp:220:22: warning: left shift count >= width of type [-Wshift-count-overflow]
  220 |     codegen_var = 1L << 33
      |                   ~~~^~~~~
/<<PKGBUILDDIR>>/src/symtab/symbol_properties.hpp:220:22: error: right operand of shift expression ‘(1 << 33)’ is greater than or equal to the precision 32 of the left operand [-fpermissive]
/<<PKGBUILDDIR>>/src/symtab/symbol_properties.hpp:220:25: error: enumerator value for ‘codegen_var’ is not an integer constant
  220 |     codegen_var = 1L << 33
      |                         ^~
```

This is an attempt to fix the same. Verified that it builds on a 32-bit chroot on v0.6.

/cc: @pramodk

### CODE REVIEW

**Comment by alkino** [comment]
As the underlying type is `long long` maybe you can use LL everywhere

**Comment by alkino** [comment]
Maybe uLL or uint64_t would be better?

**Comment by pramodk** [comment]
> As the underlying type is long long maybe you can use LL everywhere

➕ (i.e. in `NmodlType`). Otherwise, LGTM!

thanks @nileshpatra !

**Comment by nileshpatra** [comment]
> > As the underlying type is long long maybe you can use LL everywhere
> 
> ➕ (i.e. in `NmodlType`). Otherwise, LGTM!

There are other interfaces as well apart fro NmodlType that use `enum_type = long long`. I've added `LL` for all such blocks. Kindly review.

**Comment by pramodk** [comment]
> Maybe uLL or uint64_t would be better?

@alkino : ULL should be fine (/better?) as well. But as LL and ULL would typically be at least 64 bits, this should be Ok as well, right?

**Comment by alkino** [comment]
Right. I only find it more clear if this is U. I would advocate for ULL

**Comment by nileshpatra** [comment]
The Sonar CI fails with:

>ERROR: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator

I don't think I can do anything here. Can you please do the needful?

**Review by alkino — APPROVED** [review]

**Comment by alkino** [comment]
> The Sonar CI fails with:
> 
> >ERROR: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator
> 
> I don't think I can do anything here. Can you please do the needful?

We take care of that, thank you for your PR. It will merge soon or later (tomorrow).

**Comment by ohm314** [comment]
@nileshpatra, I think if you rebase your PR branch on our latest master the sonarcloud job should become non-failing.

**Comment by nileshpatra** [comment]
> @nileshpatra, I think if you rebase your PR branch on our latest master the sonarcloud job should become non-failing.

Thanks it seems green now. The remaining (docs/epfl CI) probably need your approval?
